"""Build the SA/SP Hygiene multi-sheet Excel workbook.

Output: generated-content/sa-sp-hygiene/SA_SP_Hygiene_Analysis.xlsx
"""
from openpyxl import Workbook
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
from openpyxl.utils import get_column_letter
from pathlib import Path

OUT = Path(__file__).parent / "SA_SP_Hygiene_Analysis.xlsx"

# ---------------------------------------------------------------------------
# Style helpers
# ---------------------------------------------------------------------------
HDR_FONT = Font(bold=True, color="FFFFFF", size=11)
HDR_FILL = PatternFill("solid", fgColor="1F4E78")
ALT_FILL = PatternFill("solid", fgColor="F2F2F2")
WRAP = Alignment(wrap_text=True, vertical="top")
THIN = Side(style="thin", color="BFBFBF")
BORDER = Border(left=THIN, right=THIN, top=THIN, bottom=THIN)


def write_sheet(wb, title, headers, rows, col_widths=None, freeze="A2"):
    ws = wb.create_sheet(title=title)
    ws.append(headers)
    for c, _ in enumerate(headers, 1):
        cell = ws.cell(row=1, column=c)
        cell.font = HDR_FONT
        cell.fill = HDR_FILL
        cell.alignment = Alignment(wrap_text=True, vertical="center", horizontal="center")
        cell.border = BORDER
    for r_idx, row in enumerate(rows, start=2):
        for c_idx, val in enumerate(row, start=1):
            cell = ws.cell(row=r_idx, column=c_idx, value=val)
            cell.alignment = WRAP
            cell.border = BORDER
            if r_idx % 2 == 0:
                cell.fill = ALT_FILL
    if col_widths:
        for i, w in enumerate(col_widths, 1):
            ws.column_dimensions[get_column_letter(i)].width = w
    ws.freeze_panes = freeze
    ws.row_dimensions[1].height = 32
    return ws


# ---------------------------------------------------------------------------
# Sheet 1: Summary
# ---------------------------------------------------------------------------
SUMMARY_HDR = ["#", "Issue Category", "Sheet Name", "Rows Affected",
               "% of 183", "Severity", "Auto-Fixable?", "Owner"]
SUMMARY = [
    [0, "Source Union Data (183 rows — the input)", "Source_Union_Data", 183, "100%", "Reference", "—", "—"],
    [1, "Spelling / Casing / Punctuation Variants", "Spelling_Variants", 22, "12%", "Medium", "Yes (alias map)", "Data Eng"],
    [2, "CSV Parsing / Trailing-Comma Bugs", "CSV_Parsing_Bugs", 3, "2%", "High", "Yes (fix ingestion)", "Data Eng"],
    [3, "Pure Junk Values (numeric / test strings)", "Pure_Junk_Values", 10, "5%", "High", "Yes (denylist)", "Data Eng"],
    [4, "Unknown Pollution", "Unknown_Pollution", 17, "9%", "Medium", "Partial (filter)", "Source System"],
    [5, "Legacy FY24 Taxonomy", "Legacy_Taxonomy", 65, "36%", "Medium", "Yes (lookup table)", "BI / Steward"],
    [6, "Segment / Channel Buckets Misplaced", "Segment_Channel_Buckets", 12, "7%", "Medium", "Yes (split dim)", "BI / Steward"],
    [7, "Multi-Area Plays (Conflicts)", "MultiArea_Plays", 37, "—", "High", "No (steward review)", "Steward"],
    [8, "High-Confidence Misclassifications", "Misclassifications", 11, "6%", "High", "No (steward review)", "Steward"],
    [9, "FY25 Canonical Reference Map", "FY25_Canonical_Map", "—", "—", "Reference", "—", "Steward"],
]

# ---------------------------------------------------------------------------
# Sheet 2: Spelling / Casing / Punctuation Variants
# ---------------------------------------------------------------------------
VAR_HDR = ["Row(s)", "Source SolutionArea", "Source SolutionPlay",
           "Issue", "FY25 Suggested SolutionArea", "FY25 Suggested SolutionPlay", "Notes"]
SPELLING = [
    ["109", "Security", "Modern Sec Ops", "Spacing variant",
     "Security", "Modern SecOps", "Collapse with rows 110/111"],
    ["110, 111", "Security / Cloud and AI Platforms", "Modern SecOps with Unified Platform",
     "Different Area for same Play", "Security", "Modern SecOps with Unified Platform",
     "Pick Security as canonical"],
    ["155, 157", "Security", "Threat Protection / Threat protection",
     "Case mismatch", "Security", "Threat Protection", ""],
    ["156, 158", "Security", "Threat Protection with XDR and SIEM / lowercase variant",
     "Case mismatch", "Security", "Threat Protection with XDR and SIEM", ""],
    ["164, 165", "Cloud and AI Platforms / Data and AI",
     "Unify Your Intelligent Data and Analytics Platform / lowercase variant",
     "Case mismatch + legacy Area", "Cloud and AI Platforms",
     "Unify Your Intelligent Data and Analytics Platform", ""],
    ["70, 71", "Infrastructure", "Innovate Across Hybrid and Edge with Arc and IoT / ...and loT",
     "Typo: lowercase L instead of I in 'IoT'", "Cloud and AI Platforms",
     "Innovate Across Hybrid and Edge with Arc and IoT", "Legacy Area also needs remap"],
    ["53", "Cloud and AI Platforms", "Drive Cloud Success through Unified with Enhanced Solution",
     "Missing trailing 's'", "Cloud and AI Platforms",
     "Drive Cloud Success through Unified with Enhanced Solutions", ""],
    ["59", "Unified Support", "Drive Cloud Success with Enhanced Solutions",
     "Missing 'through Unified' — partial variant", "",
     "Drive Cloud Success through Unified with Enhanced Solutions",
     "Area is a segment bucket — move to support dim"],
    ["49, 50, 51, 52", "Modern Work / Business Applications / Unknown / AI Business Solutions",
     "Drive Business Transformation with Copilot / lowercase 'transformation'",
     "Case + multi-Area", "AI Business Solutions",
     "Drive Business Transformation with Copilot", ""],
    ["94, 97", "Data and AI / Unknown", "Migrate and Modernize Your Data Estate / lowercase variant",
     "Case mismatch + Unknown Area", "Cloud and AI Platforms",
     "Migrate and Modernize Your Data Estate", ""],
    ["98, 99", "Unknown / Infrastructure",
     "Migrate and Modernize your Infrastructure and Workloads",
     "Unknown Area + legacy", "Cloud and AI Platforms",
     "Migrate and Modernize Your Infrastructure and Workloads", "Title-case 'Your'"],
    ["175", "Data & AI", "Unknown", "Ampersand vs 'and' in Area",
     "Cloud and AI Platforms", "", "Normalize Area, Play still Unknown"],
]

# ---------------------------------------------------------------------------
# Sheet 3: CSV Parsing / Trailing-Comma Bugs
# ---------------------------------------------------------------------------
CSV_HDR = ["Row", "Source SolutionArea", "Source SolutionPlay (Broken)",
           "Likely Intended SolutionPlay", "FY25 Suggested SolutionArea",
           "FY25 Suggested SolutionPlay", "Root Cause"]
CSV_BUGS = [
    [83, "Infrastructure", "Innovate with HPC, AI Infrastructure",
     "Innovate with HPC and AI Infrastructure (one play) OR two separate plays",
     "Cloud and AI Platforms", "Innovate with HPC and AI Infrastructure",
     "Unquoted comma in CSV — field split across columns"],
    [106, "Data and AI", "Migrate and Secure Windows Server, SQL",
     "Migrate and Secure Windows Server and SQL Server",
     "Cloud and AI Platforms", "Migrate and Secure Windows Server and SQL Server",
     "Unquoted comma in CSV"],
    [107, "Cloud and AI Platforms", "Migrate and Secure Windows Server, and Linux Estate",
     "Migrate and Secure Windows Server SQL and Linux Estate",
     "Cloud and AI Platforms", "Migrate and Secure Windows Server SQL and Linux Estate",
     "Unquoted comma in CSV"],
]

# ---------------------------------------------------------------------------
# Sheet 4: Pure Junk Values
# ---------------------------------------------------------------------------
JUNK_HDR = ["Row", "Source SolutionArea", "Source SolutionPlay", "Why It's Junk",
            "FY25 Suggested SolutionArea", "FY25 Suggested SolutionPlay", "Action"]
JUNK = [
    [0, "Cloud and AI Platforms", "0", "Numeric Play value", "", "", "Drop / Quarantine"],
    [1, "4", "1", "Both columns numeric", "", "", "Drop / Quarantine"],
    [25, "Unknown", "Business Applications",
     "Area name appears in Play column — inverted record", "AI Business Solutions", "",
     "Manual reclassify"],
    [35, "Unknown", "Copilot", "Generic placeholder Play", "AI Business Solutions",
     "Copilot and Agents at Work", "Best-guess remap"],
    [125, "Security Test", "Multi Cloud Security Test", "Test data leaked to PROD",
     "Security", "Multi Cloud Security", "Drop test rows"],
    [126, "Security", "Multi Cloud Security Test", "Test Play name leaked",
     "Security", "Multi Cloud Security", "Drop test rows"],
    [178, "Yes", "Unknown", "'Yes' is not a valid Area", "", "", "Drop / Quarantine"],
    [179, "5215403", "Unknown", "Numeric ID leaked into Area column", "", "",
     "Drop / Quarantine + investigate ingestion"],
    [180, "Unknown", "hi", "Obvious test typo", "", "", "Drop / Quarantine"],
    [181, "something", "who knows", "Placeholder text", "", "", "Drop / Quarantine"],
    [182, "Unknown", "null", "String literal 'null' (not actual NULL)", "", "",
     "Drop / Quarantine + fix nullability handling"],
]

# ---------------------------------------------------------------------------
# Sheet 5: Unknown Pollution
# ---------------------------------------------------------------------------
UNK_HDR = ["Row", "Source SolutionArea", "Source SolutionPlay", "Issue Type",
           "FY25 Suggested SolutionArea", "FY25 Suggested SolutionPlay", "Notes"]
UNKNOWN = [
    [5, "Unknown", "AI Ready with Surface Copilot PCs", "Area = Unknown",
     "AI Business Solutions", "AI Ready with Surface Copilot PCs", "Play implies AIBS"],
    [13, "Unknown", "Accelerate Innovation with Low Code", "Area = Unknown",
     "AI Business Solutions", "Innovate with Low Code AI and Agents", ""],
    [22, "Unknown", "Build and Modernize AI Apps", "Area = Unknown",
     "Cloud and AI Platforms", "Build and Modernize AI Apps", ""],
    [51, "Unknown", "Drive Business Transformation with Copilot", "Area = Unknown",
     "AI Business Solutions", "Drive Business Transformation with Copilot", ""],
    [97, "Unknown", "Migrate and Modernize your Data Estate", "Area = Unknown",
     "Cloud and AI Platforms", "Migrate and Modernize Your Data Estate", ""],
    [98, "Unknown", "Migrate and Modernize your Infrastructure and Workloads",
     "Area = Unknown", "Cloud and AI Platforms",
     "Migrate and Modernize Your Infrastructure and Workloads", ""],
    [128, "Unknown", "Optimize Finance and Supply Chain", "Area = Unknown",
     "AI Business Solutions", "Optimize Finance and Supply Chain", ""],
    [142, "Unknown", "AI Ready with Surface Copilot PCs", "Area = Unknown",
     "AI Business Solutions", "AI Ready with Surface Copilot PCs", "Duplicate of row 5"],
    [145, "Unknown", "Migrate and Modernize your Data Estate", "Area = Unknown",
     "Cloud and AI Platforms", "Migrate and Modernize Your Data Estate", ""],
    [148, "Unknown", "Build and Modernize AI Apps", "Area = Unknown",
     "Cloud and AI Platforms", "Build and Modernize AI Apps", "Duplicate of row 22"],
    [149, "Unknown", "Drive Business Transformation with Copilot", "Area = Unknown",
     "AI Business Solutions", "Drive Business Transformation with Copilot",
     "Duplicate of row 51"],
    [166, "AI Business Solutions", "Unknown", "Play = Unknown",
     "AI Business Solutions", "", "Placeholder — quarantine"],
    [167, "Infrastructure", "Unknown", "Play = Unknown",
     "Cloud and AI Platforms", "", "Placeholder — quarantine"],
    [168, "Unified Support", "Unknown", "Play = Unknown — Area is support bucket",
     "", "", "Move to support dim"],
    [169, "Modern Work", "Unknown", "Play = Unknown",
     "AI Business Solutions", "", "Placeholder"],
    [170, "Cloud and AI Platforms", "Unknown", "Play = Unknown",
     "Cloud and AI Platforms", "", "Placeholder"],
    [171, "Data and AI", "Unknown", "Play = Unknown",
     "Cloud and AI Platforms", "", "Placeholder"],
    [172, "Security", "Unknown", "Play = Unknown",
     "Security", "", "Placeholder"],
    [173, "Business Applications", "Unknown", "Play = Unknown",
     "AI Business Solutions", "", "Placeholder"],
    [174, "Digital and Application Innovation", "Unknown", "Play = Unknown",
     "Cloud and AI Platforms", "", "Placeholder"],
    [177, "Microsoft Unified", "Unknown", "Play = Unknown — Area is support bucket",
     "", "", "Move to support dim"],
]

# ---------------------------------------------------------------------------
# Sheet 6: Legacy FY24 Taxonomy
# ---------------------------------------------------------------------------
LEG_HDR = ["Row", "Legacy SolutionArea (FY24)", "SolutionPlay",
           "FY25 Suggested SolutionArea", "FY25 Suggested SolutionPlay", "Mapping Rule"]
LEGACY = [
    [2, "Modern Work", "AI Powered Business with Copilot", "AI Business Solutions",
     "AI Powered Business with Copilot", "Modern Work → AIBS"],
    [3, "Business Applications", "AI Powered Business with Copilot", "AI Business Solutions",
     "AI Powered Business with Copilot", "Business Applications → AIBS"],
    [7, "Digital and Application Innovation", "Accelerate Developer Productivity",
     "Cloud and AI Platforms", "Accelerate Developer Productivity", "D&AI → CAIP"],
    [9, "Digital and Application Innovation", "Accelerate Innovation with Integration Services",
     "Cloud and AI Platforms", "Accelerate Innovation with Integration Services", "D&AI → CAIP"],
    [11, "Digital and Application Innovation", "Accelerate Innovation with Low Code",
     "Cloud and AI Platforms", "Innovate with Low Code AI and Agents", "D&AI → CAIP + Play remap"],
    [12, "Business Applications", "Accelerate Innovation with Low Code",
     "AI Business Solutions", "Innovate with Low Code AI and Agents", "BizApps → AIBS"],
    [14, "Business Applications", "Accelerate Revenue Generation", "AI Business Solutions",
     "Accelerate Revenue Generation", "BizApps → AIBS"],
    [16, "Data and AI", "Advance Sustainability with an Intelligent Data Platform",
     "Cloud and AI Platforms", "Advance Sustainability with an Intelligent Data Platform",
     "Data and AI → CAIP"],
    [20, "Digital and Application Innovation", "Build and Modernize AI Apps",
     "Cloud and AI Platforms", "Build and Modernize AI Apps", "D&AI → CAIP"],
    [21, "Data and AI", "Build and Modernize AI Apps", "Cloud and AI Platforms",
     "Build and Modernize AI Apps", "Data and AI → CAIP"],
    [24, "Digital and Application Innovation", "Build your Games in the Cloud with Azure",
     "Cloud and AI Platforms", "Build your Games in the Cloud with Azure", "D&AI → CAIP"],
    [26, "Modern Work", "Cloud Endpoints", "AI Business Solutions",
     "Scale with Cloud and AI Endpoints", "Modern Work → AIBS + Play rename"],
    [28, "Modern Work", "Collaborative Apps", "AI Business Solutions",
     "Copilot and Agents at Work", "Modern Work → AIBS + Play remap"],
    [29, "Business Applications", "Connected Sales and Marketing", "AI Business Solutions",
     "Sales Transformation with AI", "BizApps → AIBS + Play remap"],
    [32, "Modern Work", "Converged Communications", "AI Business Solutions",
     "Converged Communications", "Modern Work → AIBS"],
    [33, "Modern Work", "Converged Communications Teams Phone", "AI Business Solutions",
     "Converged Communications", "Consolidate Phone/Rooms variants"],
    [34, "Modern Work", "Converged Communications Teams Rooms", "AI Business Solutions",
     "Converged Communications", "Consolidate Phone/Rooms variants"],
    [44, "Modern Work", "Data Security", "Security", "Data Security",
     "Data Security always → Security pillar"],
    [45, "Data and AI", "Data Security", "Security", "Data Security",
     "Data Security always → Security pillar"],
    [48, "Modern Work", "Digital Workforce", "AI Business Solutions",
     "Frontline Workers", "Modern Work → AIBS + Play remap"],
    [49, "Modern Work", "Drive Business Transformation with Copilot",
     "AI Business Solutions", "Drive Business Transformation with Copilot", "Modern Work → AIBS"],
    [50, "Business Applications", "Drive Business Transformation with Copilot",
     "AI Business Solutions", "Drive Business Transformation with Copilot", "BizApps → AIBS"],
    [61, "Modern Work", "Employee Experience", "AI Business Solutions",
     "Employee Experience", "Modern Work → AIBS"],
    [63, "Infrastructure", "Enable Customer Success", "",
     "Enable Customer Success", "Not a true Play — move to programs dim"],
    [64, "Modern Work", "Enable Customer Success", "",
     "Enable Customer Success", "Not a true Play"],
    [65, "Digital and Application Innovation", "Enable Developer Productivity and Accelerate Delivery",
     "Cloud and AI Platforms", "Accelerate Developer Productivity",
     "D&AI → CAIP + Play normalize"],
    [66, "Data and AI", "Enable Unified Data Governance", "Cloud and AI Platforms",
     "Unify Your Data Platform", "Data and AI → CAIP + Play remap"],
    [67, "Business Applications", "Enable a Resilient and Sustainable Supply Chain",
     "AI Business Solutions", "Scale Business Operations with AI",
     "BizApps → AIBS + Play remap"],
    [68, "Modern Work", "Frontline Workers", "AI Business Solutions",
     "Frontline Workers", "Modern Work → AIBS"],
    [70, "Infrastructure", "Innovate Across Hybrid and Edge with Arc and IoT",
     "Cloud and AI Platforms", "Innovate Across Hybrid and Edge with Arc and IoT",
     "Infra → CAIP"],
    [71, "Infrastructure", "Innovate Across Hybrid and Edge with Arc and loT (typo)",
     "Cloud and AI Platforms", "Innovate Across Hybrid and Edge with Arc and IoT",
     "Infra → CAIP + typo fix"],
    [72, "Digital and Application Innovation", "Innovate and Scale with Cloud Native Apps",
     "Cloud and AI Platforms", "Innovate and Scale with Cloud Native Apps", "D&AI → CAIP"],
    [73, "Data and AI", "Innovate with AI and Cloud Scale Databases in Every App",
     "Cloud and AI Platforms", "Innovate with AI and Cloud Scale Databases in Every App",
     "Data and AI → CAIP"],
    [74, "Business Applications", "Innovate with AI in Low Code", "AI Business Solutions",
     "Innovate with Low Code AI and Agents", "BizApps → AIBS + Play normalize"],
    [78, "Infrastructure", "Innovate with Azure AI Platform", "Cloud and AI Platforms",
     "Innovate with Azure AI Platform", "Infra → CAIP"],
    [79, "Data and AI", "Innovate with Azure AI Platform", "Cloud and AI Platforms",
     "Innovate with Azure AI Platform", "Data and AI → CAIP"],
    [81, "Infrastructure", "Innovate with HPC", "Cloud and AI Platforms",
     "Innovate with HPC", "Infra → CAIP"],
    [86, "Infrastructure", "MACC Accelerate Growth with Microsoft Azure Consumption Commitments",
     "Cloud and AI Platforms", "", "MACC is a program, not a Play"],
    [87, "Digital and Application Innovation", "Migrate Enterprise Apps",
     "Cloud and AI Platforms", "Modernize Enterprise Applications",
     "D&AI → CAIP + Play normalize"],
    [88, "Infrastructure", "Migrate Linux Estate", "Cloud and AI Platforms",
     "Migrate and Secure Windows Server SQL and Linux Estate", "Infra → CAIP + Play rollup"],
    [89, "Infrastructure", "Migrate Oracle", "Cloud and AI Platforms",
     "Migrate Oracle", "Infra → CAIP"],
    [90, "Data and AI", "Migrate Oracle", "Cloud and AI Platforms",
     "Migrate Oracle", "Data and AI → CAIP"],
    [92, "Infrastructure", "Migrate SAP", "Cloud and AI Platforms",
     "Migrate SAP", "Infra → CAIP"],
    [94, "Data and AI", "Migrate and Modernize Your Data Estate",
     "Cloud and AI Platforms", "Migrate and Modernize Your Data Estate",
     "Data and AI → CAIP"],
    [99, "Infrastructure", "Migrate and Modernize your Infrastructure and Workloads",
     "Cloud and AI Platforms",
     "Migrate and Modernize Your Infrastructure and Workloads", "Infra → CAIP"],
    [100, "Infrastructure", "Migrate and Secure Windows Server SQL and Linux Estate",
     "Cloud and AI Platforms",
     "Migrate and Secure Windows Server SQL and Linux Estate", "Infra → CAIP"],
    [102, "Data and AI", "Migrate and Secure Windows Server SQL and Linux Estate",
     "Cloud and AI Platforms",
     "Migrate and Secure Windows Server SQL and Linux Estate", "Data and AI → CAIP"],
    [103, "Data and AI", "Migrate and Secure Windows Server and SQL Server",
     "Cloud and AI Platforms",
     "Migrate and Secure Windows Server and SQL Server", "Data and AI → CAIP"],
    [104, "Infrastructure", "Migrate and Secure Windows Server and SQL Server",
     "Cloud and AI Platforms",
     "Migrate and Secure Windows Server and SQL Server", "Infra → CAIP"],
    [112, "Business Applications", "Modernize ERP", "AI Business Solutions",
     "ERP Transformation with AI", "BizApps → AIBS + Play rename"],
    [114, "Digital and Application Innovation", "Modernize Enterprise Applications",
     "Cloud and AI Platforms", "Modernize Enterprise Applications", "D&AI → CAIP"],
    [115, "Infrastructure", "Modernize SAP on the Microsoft Cloud",
     "Cloud and AI Platforms", "Migrate SAP", "Infra → CAIP + Play consolidate"],
    [116, "Business Applications", "Modernize Service", "AI Business Solutions",
     "Service Transformation with AI", "BizApps → AIBS + Play rename"],
    [118, "Business Applications", "Modernize the Service Experience",
     "AI Business Solutions", "Service Transformation with AI",
     "BizApps → AIBS + Play normalize"],
    [119, "Modern Work", "Modernize with Surface", "AI Business Solutions",
     "Modernize with Surface", "Modern Work → AIBS"],
    [121, "Infrastructure", "Modernize your Workloads with Azure at any Scale with HPC plus AI",
     "Cloud and AI Platforms", "Innovate with HPC", "Infra → CAIP + Play consolidate"],
    [122, "Infrastructure", "Modernizing Mainframe", "Cloud and AI Platforms",
     "Modernizing Mainframe", "Infra → CAIP"],
    [127, "Modern Work", "NextGen Windows Experiences", "AI Business Solutions",
     "Modernize with Surface", "Modern Work → AIBS + Play consolidate"],
    [129, "Business Applications", "Optimize Finance and Supply Chain",
     "AI Business Solutions", "Scale Business Operations with AI",
     "BizApps → AIBS + Play remap"],
    [130, "Data and AI", "Power Business Decisions with Cloud Scale Analytics",
     "Cloud and AI Platforms", "Unify Your Intelligent Data and Analytics Platform",
     "Data and AI → CAIP + Play remap"],
    [134, "Infrastructure", "Protect your Data and Ensure Business Resiliency with BCDR",
     "Cloud and AI Platforms",
     "Protect your Data and Ensure Business Resiliency with BCDR", "Infra → CAIP"],
    [135, "Modern Work", "Refresh your Devices", "AI Business Solutions",
     "Modernize with Surface", "Modern Work → AIBS + Play consolidate"],
    [136, "Business Applications", "SMB Scale Business Operations",
     "AI Business Solutions", "Scale Business Operations with AI",
     "BizApps → AIBS + Play normalize"],
    [139, "Business Applications", "Scale Business Operations", "AI Business Solutions",
     "Scale Business Operations with AI", "BizApps → AIBS"],
    [152, "Modern Work", "Secure Productivity", "Security", "Secure Productivity",
     "Productivity-security → Security pillar"],
    [163, "Data and AI", "Unify Your Intelligent Data and Analytics Platform",
     "Cloud and AI Platforms", "Unify Your Intelligent Data and Analytics Platform",
     "Data and AI → CAIP"],
    [165, "Data and AI", "Unify your Intelligent Data and Analytics Platform",
     "Cloud and AI Platforms", "Unify Your Intelligent Data and Analytics Platform",
     "Data and AI → CAIP + case fix"],
]

# ---------------------------------------------------------------------------
# Sheet 7: Segment / Channel Buckets Misplaced
# ---------------------------------------------------------------------------
SEG_HDR = ["Row", "Non-SA Bucket", "SolutionPlay", "Real Dimension It Belongs To",
           "FY25 Suggested SolutionArea (if Play valid)", "FY25 Suggested SolutionPlay", "Notes"]
SEGMENT = [
    [6, "Unified Support", "Accelerate AI innovation for Digital Natives with Unified",
     "DimSupportContract", "", "", "Support contract — not a SA"],
    [19, "Unified Support", "Build a Strong Foundation with Unified",
     "DimSupportContract", "", "", ""],
    [39, "Modern Life", "Copilot and Agents at Work", "DimSegment (Consumer)",
     "AI Business Solutions", "Copilot and Agents at Work",
     "Modern Life is consumer segment — Play is generic AIBS"],
    [40, "Nuance Healthcare", "Copilot and Agents at Work", "DimBusinessUnit",
     "AI Business Solutions", "Copilot and Agents at Work",
     "Acquired BU — Play is generic AIBS"],
    [54, "Microsoft Unified", "Drive Cloud Success through Unified with Enhanced Solutions",
     "DimSupportContract", "", "", ""],
    [58, "Support", "Drive Cloud Success through Unified with Enhanced Solutions",
     "DimSupportContract", "", "", ""],
    [59, "Unified Support", "Drive Cloud Success with Enhanced Solutions",
     "DimSupportContract", "", "", ""],
    [77, "Azure Cloud Billed", "Innovate with Azure AI Apps and Agents",
     "DimBillingChannel", "Cloud and AI Platforms",
     "Innovate with Azure AI Apps and Agents", "Azure Cloud Billed is billing flag"],
    [125, "Security Test", "Multi Cloud Security Test", "TEST environment",
     "Security", "Multi Cloud Security", "Drop — test data"],
    [142, "Unified Support", "Scale Unified through Partner",
     "DimSupportContract", "", "", ""],
    [161, "Azure Cloud Billed", "Unify Your Data Platform", "DimBillingChannel",
     "Cloud and AI Platforms", "Unify Your Data Platform", ""],
    [168, "Unified Support", "Unknown", "DimSupportContract", "", "", ""],
    [177, "Microsoft Unified", "Unknown", "DimSupportContract", "", "", ""],
]

# ---------------------------------------------------------------------------
# Sheet 8: Multi-Area Plays
# ---------------------------------------------------------------------------
MULTI_HDR = ["SolutionPlay", "# Distinct Areas", "Areas Seen (raw)",
             "FY25 Suggested SolutionArea", "Tie-Breaker Reason"]
MULTI = [
    ["Copilot and Agents at Work", 5,
     "AI Business Solutions; Cloud and AI Platforms; Security; Modern Life; Nuance Healthcare",
     "AI Business Solutions", "Productivity Copilot is core AIBS"],
    ["Data Security", 4,
     "Security; Modern Work; Data and AI; AI Business Solutions",
     "Security", "Always Security pillar"],
    ["Drive Cloud Success through Unified with Enhanced Solutions", 5,
     "Microsoft Unified; Cloud and AI Platforms; AI Business Solutions; Security; Support",
     "", "Move to Support dim — not a real Play"],
    ["Unify Your Data Platform", 4,
     "Security; Cloud and AI Platforms; Azure Cloud Billed; AI Business Solutions",
     "Cloud and AI Platforms", "Data platform = CAIP"],
    ["Scale with Cloud and AI Endpoints", 3,
     "AI Business Solutions; Cloud and AI Platforms; Security",
     "AI Business Solutions", "Endpoints attach to AIBS in FY25"],
    ["Converged Communications", 3,
     "AI Business Solutions; Security; Modern Work",
     "AI Business Solutions", "Teams Phone/Rooms = AIBS"],
    ["Drive Business Transformation with Copilot", 3,
     "Modern Work; Business Applications; Unknown; AI Business Solutions",
     "AI Business Solutions", "Copilot transformation = AIBS"],
    ["Build and Modernize AI Apps", 4,
     "Digital and Application Innovation; Data and AI; Unknown; Cloud and AI Platforms",
     "Cloud and AI Platforms", "AI Apps = CAIP"],
    ["Innovate with Azure AI Platform", 3,
     "Infrastructure; Data and AI; Cloud and AI Platforms",
     "Cloud and AI Platforms", "Azure platform = CAIP"],
    ["Migrate Oracle", 3,
     "Infrastructure; Data and AI; Cloud and AI Platforms",
     "Cloud and AI Platforms", "Migration = CAIP"],
    ["Modernize ERP", 2,
     "Business Applications; AI Business Solutions",
     "AI Business Solutions", "FY25 collapses BizApps into AIBS"],
    ["Modernize Service", 2,
     "Business Applications; AI Business Solutions",
     "AI Business Solutions", "Same"],
    ["Modernize with Surface", 2,
     "Modern Work; AI Business Solutions",
     "AI Business Solutions", "Same"],
    ["Frontline Workers", 2,
     "Modern Work; AI Business Solutions",
     "AI Business Solutions", "Same"],
    ["Employee Experience", 2,
     "Modern Work; AI Business Solutions",
     "AI Business Solutions", "Same"],
    ["Cloud Endpoints", 2,
     "Modern Work; AI Business Solutions",
     "AI Business Solutions", "Same"],
    ["Innovate with Low Code AI and Agents", 2,
     "Cloud and AI Platforms; AI Business Solutions",
     "AI Business Solutions", "Low Code = business app territory"],
    ["Accelerate Developer Productivity", 2,
     "Digital and Application Innovation; Cloud and AI Platforms",
     "Cloud and AI Platforms", "Developer = CAIP"],
    ["Accelerate Innovation with Integration Services", 2,
     "Digital and Application Innovation; Cloud and AI Platforms",
     "Cloud and AI Platforms", "Integration = CAIP"],
    ["Accelerate Innovation with Low Code", 3,
     "Digital and Application Innovation; Business Applications; Unknown",
     "AI Business Solutions", "Map to 'Innovate with Low Code AI and Agents'"],
    ["Accelerate Revenue Generation", 2,
     "Business Applications; AI Business Solutions",
     "AI Business Solutions", "Same"],
    ["Migrate SAP", 2,
     "Infrastructure; Cloud and AI Platforms",
     "Cloud and AI Platforms", "Migration = CAIP"],
    ["Migrate and Modernize Your Estate", 2,
     "Security; Cloud and AI Platforms",
     "Cloud and AI Platforms", "Migration = CAIP"],
    ["Modernizing Mainframe", 2,
     "Infrastructure; Cloud and AI Platforms",
     "Cloud and AI Platforms", "Migration = CAIP"],
    ["Innovate with HPC", 2,
     "Infrastructure; Cloud and AI Platforms",
     "Cloud and AI Platforms", "Infra → CAIP"],
    ["Advance Sustainability with an Intelligent Data Platform", 2,
     "Data and AI; Cloud and AI Platforms",
     "Cloud and AI Platforms", "Data platform = CAIP"],
    ["Innovate with Azure AI Apps and Agents", 2,
     "Cloud and AI Platforms; Azure Cloud Billed",
     "Cloud and AI Platforms", "Drop billing-channel"],
    ["Sales Transformation with AI", 2,
     "AI Business Solutions; Security",
     "AI Business Solutions", "Security row is a data-entry error"],
    ["Secure AI Productivity", 2,
     "Security; AI Business Solutions",
     "Security", "Security framing dominates"],
    ["Secure Productivity", 3,
     "Security; Modern Work; AI Business Solutions",
     "Security", "Security framing dominates"],
    ["Enable Customer Success", 2,
     "Infrastructure; Modern Work",
     "", "Not a real Play — programs/CSM motion"],
    ["AI Powered Business with Copilot", 2,
     "Modern Work; Business Applications",
     "AI Business Solutions", "Both legacy → AIBS"],
    ["Innovate with AI in Low Code", 2,
     "Business Applications; AI Business Solutions",
     "AI Business Solutions", "Same"],
    ["Migrate and Secure Windows Server SQL and Linux Estate", 3,
     "Infrastructure; Security; Data and AI",
     "Cloud and AI Platforms", "Migration motion = CAIP"],
    ["Migrate and Secure Windows Server and SQL Server", 3,
     "Data and AI; Infrastructure; Security",
     "Cloud and AI Platforms", "Migration motion = CAIP"],
    ["Protect Cloud AI Platform and Apps", 2,
     "Security; Cloud and AI Platforms",
     "Security", "Protection = Security"],
    ["AI Ready with Surface Copilot PCs", 2,
     "AI Business Solutions; Unknown",
     "AI Business Solutions", "Drop Unknown row"],
]

# ---------------------------------------------------------------------------
# Sheet 9: High-Confidence Misclassifications
# ---------------------------------------------------------------------------
MIS_HDR = ["Row", "Source SolutionArea (Wrong)", "SolutionPlay",
           "Why It's Wrong", "FY25 Suggested SolutionArea",
           "FY25 Suggested SolutionPlay"]
MIS = [
    [138, "Security", "Sales Transformation with AI",
     "Sales = AI Business Solutions, not Security",
     "AI Business Solutions", "Sales Transformation with AI"],
    [145, "Security", "Scale with Cloud and AI Endpoints",
     "Endpoints = AIBS/CAIP, not Security",
     "AI Business Solutions", "Scale with Cloud and AI Endpoints"],
    [31, "Security", "Converged Communications",
     "Comms = AIBS/Modern Work, not Security",
     "AI Business Solutions", "Converged Communications"],
    [38, "Security", "Copilot and Agents at Work",
     "Generic Copilot Play — belongs to AIBS",
     "AI Business Solutions", "Copilot and Agents at Work"],
    [162, "AI Business Solutions", "Unify Your Data Platform",
     "Data Platform = CAIP",
     "Cloud and AI Platforms", "Unify Your Data Platform"],
    [46, "AI Business Solutions", "Data Security",
     "Data Security = Security pillar",
     "Security", "Data Security"],
    [153, "AI Business Solutions", "Secure Productivity",
     "Secure Productivity = Security pillar",
     "Security", "Secure Productivity"],
    [161, "Azure Cloud Billed", "Unify Your Data Platform",
     "Azure Cloud Billed is a billing flag, not a SA",
     "Cloud and AI Platforms", "Unify Your Data Platform"],
    [77, "Azure Cloud Billed", "Innovate with Azure AI Apps and Agents",
     "Same — billing channel, not a SA",
     "Cloud and AI Platforms", "Innovate with Azure AI Apps and Agents"],
    [95, "Security", "Migrate and Modernize Your Estate",
     "Migration motion = CAIP, not Security",
     "Cloud and AI Platforms", "Migrate and Modernize Your Estate"],
    [86, "Infrastructure", "MACC Accelerate Growth with Microsoft Azure Consumption Commitments",
     "MACC is a commercial program, not a SA Play",
     "Cloud and AI Platforms", ""],
]

# ---------------------------------------------------------------------------
# Sheet 10: FY25 Canonical Reference Map
# ---------------------------------------------------------------------------
# ---------------------------------------------------------------------------
# Sheet 0: Source Union Data — the 183-row input every other sheet references
# ---------------------------------------------------------------------------
SRC_HDR = ["Row", "SolutionArea (Raw)", "SolutionPlay (Raw)"]
SOURCE_ROWS = [
    (0, "Cloud and AI Platforms", "0"),
    (1, "4", "1"),
    (2, "Modern Work", "AI Powered Business with Copilot"),
    (3, "Business Applications", "AI Powered Business with Copilot"),
    (4, "AI Business Solutions", "AI Ready with Surface Copilot PCs"),
    (5, "Unknown", "AI Ready with Surface Copilot PCs"),
    (6, "Unified Support", "Accelerate AI innovation for Digital Natives with Unified"),
    (7, "Digital and Application Innovation", "Accelerate Developer Productivity"),
    (8, "Cloud and AI Platforms", "Accelerate Developer Productivity"),
    (9, "Digital and Application Innovation", "Accelerate Innovation with Integration Services"),
    (10, "Cloud and AI Platforms", "Accelerate Innovation with Integration Services"),
    (11, "Digital and Application Innovation", "Accelerate Innovation with Low Code"),
    (12, "Business Applications", "Accelerate Innovation with Low Code"),
    (13, "Unknown", "Accelerate Innovation with Low Code"),
    (14, "Business Applications", "Accelerate Revenue Generation"),
    (15, "AI Business Solutions", "Accelerate Revenue Generation"),
    (16, "Data and AI", "Advance Sustainability with an Intelligent Data Platform"),
    (17, "Cloud and AI Platforms", "Advance Sustainability with an Intelligent Data Platform"),
    (18, "Security", "Advanced Identity"),
    (19, "Unified Support", "Build a Strong Foundation with Unified"),
    (20, "Digital and Application Innovation", "Build and Modernize AI Apps"),
    (21, "Data and AI", "Build and Modernize AI Apps"),
    (22, "Unknown", "Build and Modernize AI Apps"),
    (23, "Cloud and AI Platforms", "Build and Modernize AI Apps"),
    (24, "Digital and Application Innovation", "Build your Games in the Cloud with Azure"),
    (25, "Unknown", "Business Applications"),
    (26, "Modern Work", "Cloud Endpoints"),
    (27, "AI Business Solutions", "Cloud Endpoints"),
    (28, "Modern Work", "Collaborative Apps"),
    (29, "Business Applications", "Connected Sales and Marketing"),
    (30, "AI Business Solutions", "Converged Communications"),
    (31, "Security", "Converged Communications"),
    (32, "Modern Work", "Converged Communications"),
    (33, "Modern Work", "Converged Communications Teams Phone"),
    (34, "Modern Work", "Converged Communications Teams Rooms"),
    (35, "Unknown", "Copilot"),
    (36, "AI Business Solutions", "Copilot and Agents at Work"),
    (37, "Cloud and AI Platforms", "Copilot and Agents at Work"),
    (38, "Security", "Copilot and Agents at Work"),
    (39, "Modern Life", "Copilot and Agents at Work"),
    (40, "Nuance Healthcare", "Copilot and Agents at Work"),
    (41, "Security", "Copilot for Security"),
    (42, "Security", "Data Governance"),
    (43, "Security", "Data Security"),
    (44, "Modern Work", "Data Security"),
    (45, "Data and AI", "Data Security"),
    (46, "AI Business Solutions", "Data Security"),
    (47, "Security", "Defend Against Threats with SIEM Plus XDR"),
    (48, "Modern Work", "Digital Workforce"),
    (49, "Modern Work", "Drive Business Transformation with Copilot"),
    (50, "Business Applications", "Drive Business Transformation with Copilot"),
    (51, "Unknown", "Drive Business Transformation with Copilot"),
    (52, "AI Business Solutions", "Drive Business transformation with Copilot"),
    (53, "Cloud and AI Platforms", "Drive Cloud Success through Unified with Enhanced Solution"),
    (54, "Microsoft Unified", "Drive Cloud Success through Unified with Enhanced Solutions"),
    (55, "Cloud and AI Platforms", "Drive Cloud Success through Unified with Enhanced Solutions"),
    (56, "AI Business Solutions", "Drive Cloud Success through Unified with Enhanced Solutions"),
    (57, "Security", "Drive Cloud Success through Unified with Enhanced Solutions"),
    (58, "Support", "Drive Cloud Success through Unified with Enhanced Solutions"),
    (59, "Unified Support", "Drive Cloud Success with Enhanced Solutions"),
    (60, "AI Business Solutions", "ERP Transformation with AI"),
    (61, "Modern Work", "Employee Experience"),
    (62, "AI Business Solutions", "Employee Experience"),
    (63, "Infrastructure", "Enable Customer Success"),
    (64, "Modern Work", "Enable Customer Success"),
    (65, "Digital and Application Innovation", "Enable Developer Productivity and Accelerate Delivery"),
    (66, "Data and AI", "Enable Unified Data Governance"),
    (67, "Business Applications", "Enable a Resilient and Sustainable Supply Chain"),
    (68, "Modern Work", "Frontline Workers"),
    (69, "AI Business Solutions", "Frontline Workers"),
    (70, "Infrastructure", "Innovate Across Hybrid and Edge with Arc and IoT"),
    (71, "Infrastructure", "Innovate Across Hybrid and Edge with Arc and loT"),
    (72, "Digital and Application Innovation", "Innovate and Scale with Cloud Native Apps"),
    (73, "Data and AI", "Innovate with AI and Cloud Scale Databases in Every App"),
    (74, "Business Applications", "Innovate with AI in Low Code"),
    (75, "AI Business Solutions", "Innovate with AI in Low Code"),
    (76, "Cloud and AI Platforms", "Innovate with Azure AI Apps and Agents"),
    (77, "Azure Cloud Billed", "Innovate with Azure AI Apps and Agents"),
    (78, "Infrastructure", "Innovate with Azure AI Platform"),
    (79, "Data and AI", "Innovate with Azure AI Platform"),
    (80, "Cloud and AI Platforms", "Innovate with Azure AI Platform"),
    (81, "Infrastructure", "Innovate with HPC"),
    (82, "Cloud and AI Platforms", "Innovate with HPC"),
    (83, "Infrastructure", "Innovate with HPC, AI Infrastructure"),
    (84, "Cloud and AI Platforms", "Innovate with Low Code AI and Agents"),
    (85, "AI Business Solutions", "Innovate with Low Code AI and Agents"),
    (86, "Infrastructure", "MACC Accelerate Growth with Microsoft Azure Consumption Commitments"),
    (87, "Digital and Application Innovation", "Migrate Enterprise Apps"),
    (88, "Infrastructure", "Migrate Linux Estate"),
    (89, "Infrastructure", "Migrate Oracle"),
    (90, "Data and AI", "Migrate Oracle"),
    (91, "Cloud and AI Platforms", "Migrate Oracle"),
    (92, "Infrastructure", "Migrate SAP"),
    (93, "Cloud and AI Platforms", "Migrate SAP"),
    (94, "Data and AI", "Migrate and Modernize Your Data Estate"),
    (95, "Security", "Migrate and Modernize Your Estate"),
    (96, "Cloud and AI Platforms", "Migrate and Modernize Your Estate"),
    (97, "Unknown", "Migrate and Modernize your Data Estate"),
    (98, "Unknown", "Migrate and Modernize your Infrastructure and Workloads"),
    (99, "Infrastructure", "Migrate and Modernize your Infrastructure and Workloads"),
    (100, "Infrastructure", "Migrate and Secure Windows Server SQL and Linux Estate"),
    (101, "Security", "Migrate and Secure Windows Server SQL and Linux Estate"),
    (102, "Data and AI", "Migrate and Secure Windows Server SQL and Linux Estate"),
    (103, "Data and AI", "Migrate and Secure Windows Server and SQL Server"),
    (104, "Infrastructure", "Migrate and Secure Windows Server and SQL Server"),
    (105, "Security", "Migrate and Secure Windows Server and SQL Server"),
    (106, "Data and AI", "Migrate and Secure Windows Server, SQL"),
    (107, "Cloud and AI Platforms", "Migrate and Secure Windows Server, and Linux Estate"),
    (108, "Security", "Mitigate Compliance and Privacy Risks"),
    (109, "Security", "Modern Sec Ops"),
    (110, "Security", "Modern SecOps with Unified Platform"),
    (111, "Cloud and AI Platforms", "Modern SecOps with Unified Platform"),
    (112, "Business Applications", "Modernize ERP"),
    (113, "AI Business Solutions", "Modernize ERP"),
    (114, "Digital and Application Innovation", "Modernize Enterprise Applications"),
    (115, "Infrastructure", "Modernize SAP on the Microsoft Cloud"),
    (116, "Business Applications", "Modernize Service"),
    (117, "AI Business Solutions", "Modernize Service"),
    (118, "Business Applications", "Modernize the Service Experience"),
    (119, "Modern Work", "Modernize with Surface"),
    (120, "AI Business Solutions", "Modernize with Surface"),
    (121, "Infrastructure", "Modernize your Workloads with Azure at any Scale with HPC plus AI"),
    (122, "Infrastructure", "Modernizing Mainframe"),
    (123, "Cloud and AI Platforms", "Modernizing Mainframe"),
    (124, "Security", "Multi Cloud Security"),
    (125, "Security Test", "Multi Cloud Security Test"),
    (126, "Security", "Multi Cloud Security Test"),
    (127, "Modern Work", "NextGen Windows Experiences"),
    (128, "Unknown", "Optimize Finance and Supply Chain"),
    (129, "Business Applications", "Optimize Finance and Supply Chain"),
    (130, "Data and AI", "Power Business Decisions with Cloud Scale Analytics"),
    (131, "Security", "Protect Cloud AI Platform and Apps"),
    (132, "Cloud and AI Platforms", "Protect Cloud AI Platform and Apps"),
    (133, "Security", "Protect and Govern Sensitive Data"),
    (134, "Infrastructure", "Protect your Data and Ensure Business Resiliency with BCDR"),
    (135, "Modern Work", "Refresh your Devices"),
    (136, "Business Applications", "SMB Scale Business Operations"),
    (137, "AI Business Solutions", "Sales Transformation with AI"),
    (138, "Security", "Sales Transformation with AI"),
    (139, "Business Applications", "Scale Business Operations"),
    (140, "AI Business Solutions", "Scale Business Operations"),
    (141, "AI Business Solutions", "Scale Business Operations with AI"),
    (142, "Unified Support", "Scale Unified through Partner"),
    (143, "AI Business Solutions", "Scale with Cloud and AI Endpoints"),
    (144, "Cloud and AI Platforms", "Scale with Cloud and AI Endpoints"),
    (145, "Security", "Scale with Cloud and AI Endpoints"),
    (146, "Security", "Secure AI Productivity"),
    (147, "AI Business Solutions", "Secure AI Productivity"),
    (148, "Security", "Secure Identities and Access"),
    (149, "Security", "Secure Identity and takeout Okta and Ping"),
    (150, "Security", "Secure Multi Cloud Environments"),
    (151, "Security", "Secure Productivity"),
    (152, "Modern Work", "Secure Productivity"),
    (153, "AI Business Solutions", "Secure Productivity"),
    (154, "AI Business Solutions", "Service Transformation with AI"),
    (155, "Security", "Threat Protection"),
    (156, "Security", "Threat Protection with XDR and SIEM"),
    (157, "Security", "Threat protection"),
    (158, "Security", "Threat protection with XDR and SIEM"),
    (159, "Security", "Unify Your Data Platform"),
    (160, "Cloud and AI Platforms", "Unify Your Data Platform"),
    (161, "Azure Cloud Billed", "Unify Your Data Platform"),
    (162, "AI Business Solutions", "Unify Your Data Platform"),
    (163, "Data and AI", "Unify Your Intelligent Data and Analytics Platform"),
    (164, "Cloud and AI Platforms", "Unify Your Intelligent Data and Analytics Platform"),
    (165, "Data and AI", "Unify your Intelligent Data and Analytics Platform"),
    (166, "AI Business Solutions", "Unknown"),
    (167, "Infrastructure", "Unknown"),
    (168, "Unified Support", "Unknown"),
    (169, "Modern Work", "Unknown"),
    (170, "Cloud and AI Platforms", "Unknown"),
    (171, "Data and AI", "Unknown"),
    (172, "Security", "Unknown"),
    (173, "Business Applications", "Unknown"),
    (174, "Digital and Application Innovation", "Unknown"),
    (175, "Data & AI", "Unknown"),
    (176, "Unknown", "Unknown"),
    (177, "Microsoft Unified", "Unknown"),
    (178, "Yes", "Unknown"),
    (179, "5215403", "Unknown"),
    (180, "Unknown", "hi"),
    (181, "something", "who knows"),
    (182, "Unknown", "null"),
]

CAN_HDR = ["FY25 SolutionArea", "FY25 SolutionPlay (Canonical)", "Notes"]
CANONICAL = [
    # AI Business Solutions
    ["AI Business Solutions", "Copilot and Agents at Work", ""],
    ["AI Business Solutions", "Secure AI Productivity", ""],
    ["AI Business Solutions", "Drive Business Transformation with Copilot", ""],
    ["AI Business Solutions", "AI Powered Business with Copilot", ""],
    ["AI Business Solutions", "AI Ready with Surface Copilot PCs", ""],
    ["AI Business Solutions", "Modernize with Surface", ""],
    ["AI Business Solutions", "Frontline Workers", ""],
    ["AI Business Solutions", "Employee Experience", ""],
    ["AI Business Solutions", "Converged Communications", "Includes Teams Phone/Rooms"],
    ["AI Business Solutions", "Scale with Cloud and AI Endpoints", ""],
    ["AI Business Solutions", "Cloud Endpoints", "Legacy alias of above"],
    ["AI Business Solutions", "ERP Transformation with AI", ""],
    ["AI Business Solutions", "Service Transformation with AI", ""],
    ["AI Business Solutions", "Sales Transformation with AI", ""],
    ["AI Business Solutions", "Scale Business Operations with AI", ""],
    ["AI Business Solutions", "Accelerate Revenue Generation", ""],
    ["AI Business Solutions", "Innovate with Low Code AI and Agents", ""],
    # Cloud and AI Platforms
    ["Cloud and AI Platforms", "Innovate with Azure AI Apps and Agents", ""],
    ["Cloud and AI Platforms", "Innovate with Azure AI Platform", ""],
    ["Cloud and AI Platforms", "Build and Modernize AI Apps", ""],
    ["Cloud and AI Platforms", "Accelerate Developer Productivity", ""],
    ["Cloud and AI Platforms", "Accelerate Innovation with Integration Services", ""],
    ["Cloud and AI Platforms", "Innovate and Scale with Cloud Native Apps", ""],
    ["Cloud and AI Platforms", "Modernize Enterprise Applications", ""],
    ["Cloud and AI Platforms", "Unify Your Data Platform", ""],
    ["Cloud and AI Platforms", "Unify Your Intelligent Data and Analytics Platform", ""],
    ["Cloud and AI Platforms", "Advance Sustainability with an Intelligent Data Platform", ""],
    ["Cloud and AI Platforms", "Migrate and Modernize Your Estate", ""],
    ["Cloud and AI Platforms", "Migrate and Modernize Your Data Estate", ""],
    ["Cloud and AI Platforms", "Migrate and Modernize Your Infrastructure and Workloads", ""],
    ["Cloud and AI Platforms", "Migrate and Secure Windows Server SQL and Linux Estate", ""],
    ["Cloud and AI Platforms", "Migrate Oracle", ""],
    ["Cloud and AI Platforms", "Migrate SAP", ""],
    ["Cloud and AI Platforms", "Modernizing Mainframe", ""],
    ["Cloud and AI Platforms", "Innovate with HPC and AI Infrastructure", ""],
    ["Cloud and AI Platforms", "Innovate Across Hybrid and Edge with Arc and IoT", ""],
    ["Cloud and AI Platforms", "Protect your Data and Ensure Business Resiliency with BCDR", ""],
    # Security
    ["Security", "Data Security", ""],
    ["Security", "Threat Protection with XDR and SIEM", "Also covers 'Modern SecOps with Unified Platform'"],
    ["Security", "Protect Cloud AI Platform and Apps", ""],
    ["Security", "Multi Cloud Security", ""],
    ["Security", "Secure Multi Cloud Environments", ""],
    ["Security", "Secure Identities and Access", "Includes Advanced Identity"],
    ["Security", "Mitigate Compliance and Privacy Risks", ""],
    ["Security", "Protect and Govern Sensitive Data", ""],
    ["Security", "Data Governance", ""],
    ["Security", "Secure Productivity", ""],
    ["Security", "Copilot for Security", ""],
]


# ---------------------------------------------------------------------------
# Build the workbook
# ---------------------------------------------------------------------------
def build():
    wb = Workbook()
    wb.remove(wb.active)

    write_sheet(wb, "Summary", SUMMARY_HDR, SUMMARY,
                col_widths=[5, 45, 28, 14, 10, 12, 22, 16])
    write_sheet(wb, "Source_Union_Data", SRC_HDR, SOURCE_ROWS,
                col_widths=[8, 38, 70])
    write_sheet(wb, "Spelling_Variants", VAR_HDR, SPELLING,
                col_widths=[12, 30, 50, 38, 28, 50, 35])
    write_sheet(wb, "CSV_Parsing_Bugs", CSV_HDR, CSV_BUGS,
                col_widths=[6, 22, 50, 55, 28, 55, 38])
    write_sheet(wb, "Pure_Junk_Values", JUNK_HDR, JUNK,
                col_widths=[6, 22, 35, 50, 28, 38, 35])
    write_sheet(wb, "Unknown_Pollution", UNK_HDR, UNKNOWN,
                col_widths=[6, 35, 55, 30, 28, 55, 35])
    write_sheet(wb, "Legacy_Taxonomy", LEG_HDR, LEGACY,
                col_widths=[6, 35, 55, 28, 55, 45])
    write_sheet(wb, "Segment_Channel_Buckets", SEG_HDR, SEGMENT,
                col_widths=[6, 22, 55, 24, 32, 55, 35])
    write_sheet(wb, "MultiArea_Plays", MULTI_HDR, MULTI,
                col_widths=[55, 14, 70, 28, 45])
    write_sheet(wb, "Misclassifications", MIS_HDR, MIS,
                col_widths=[6, 28, 55, 50, 28, 50])
    write_sheet(wb, "FY25_Canonical_Map", CAN_HDR, CANONICAL,
                col_widths=[26, 55, 40])

    OUT.parent.mkdir(parents=True, exist_ok=True)
    wb.save(OUT)
    print(f"Wrote {OUT}")


if __name__ == "__main__":
    build()
